apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-config
  labels:
    app.kubernetes.io/name: pgbouncer
    app.kubernetes.io/component: database
data:
  pgbouncer.ini: |
    [databases]
    hospital_erp = host=postgres port=5432 dbname=hospital_erp

    [pgbouncer]
    listen_addr = 0.0.0.0
    listen_port = 6432
    auth_type = md5
    auth_file = /etc/pgbouncer/userlist.txt
    pool_mode = transaction
    default_pool_size = 20
    min_pool_size = 5
    max_client_conn = 200
    max_db_connections = 50
    server_tls_sslmode = require
    log_connections = 1
    log_disconnections = 1
    log_pooler_errors = 1
    stats_period = 60
    server_idle_timeout = 600
    server_lifetime = 3600
    client_idle_timeout = 0
    query_wait_timeout = 120
