name: Feature Request
description: Suggest a new feature or enhancement
title: '[Feature]: '
labels: ['type:feature', 'status:triage']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
    validations:
      required: false

  - type: dropdown
    id: module
    attributes:
      label: Related Module
      description: Which module does this feature relate to?
      options:
        - Authentication (auth)
        - Patient Management (patient)
        - Room Management (room)
        - Admission (admission)
        - Vital Signs/Reports (report)
        - Rounding (rounding)
        - Administration (admin)
        - Frontend UI
        - Infrastructure/DevOps
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Suggested Priority
      description: How important is this feature?
      options:
        - High (Core functionality)
        - Medium (Important but not critical)
        - Low (Nice to have)
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
